config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/tournaments')

  #get 'home/index'

  resources :tournaments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :manage, :all

    else

      can :update, Tournament do |tournament|
        tournament.user == user
      end

      can :destroy, Tournament do |tournament|
        tournament.user == user
      end

      can :create, Tournament

    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user

  def self.search(search)
  	if search
  		where(["name LIKE ?","%#{search}%"])
  	else 
  		all
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tournaments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to tournaments_url, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if user_signed_in?
      redirect_to tournaments_path
    end
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
    @tournaments = Tournament.search(params[:search])

  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    #authorize! :update, @tournament
  end

  # GET /tournaments/new
  def new
    #authorize! :create, @tournament
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
    authorize! :update, @tournament
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @user = current_user
    @tournament = @user.tournaments.build(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :modality, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eChamps</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">eChamps</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/tournaments">Tournaments</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <% if user_signed_in? %>
  Bem vindo, <%= current_user.email %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign In", new_user_session_path %>
  <% end %>

  <div class="container">
    <div class="container">
      <%= yield %>
    </div>
  </div>

  <footer>
    <div class="container">
      Igor Aragão e Miguel Alves - 2017
    </div>
  </footer>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>

</body>
</html>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tournament_name %>
  </div>

  <div class="field">
    <%= form.label :modality %>
    <%= form.text_field :modality, id: :tournament_modality %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :tournament_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :tournament_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournaments</h1>
<%= flash[:alert] %>

  <%= link_to 'New Tournament', new_tournament_path %>

  <%= form_tag tournaments_path,:method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <%end%>
<br>
<br>

<% @tournaments.each do |tournament| %>
    <div style="border: 1px solid black;">
      <h2><%= tournament.name %></h2>
      <%= tournament.description %>
      <br>
      <%= time_ago_in_words(tournament.created_at) %> ago by <%= tournament.user.email %>
      <br>


      <%= link_to 'Show', tournament %>

      <% if can? :update, tournament %>
        <%= link_to 'Edit', edit_tournament_path(tournament) %>
      <% end %>

      <% if can? :destroy, tournament %>
        <%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

      <br>
      </div>
<% end %>

<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Modality</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <h3><%= tournament.name %></h3>
        <%= time_ago_in_words(tournament.created_at) %> ago by <%= tournament.user.email %>
        <td><%= tournament.modality %></td>
        <td><%= tournament.description %></td>
        <td><%= tournament.picture %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
-->

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Modality:</strong>
  <%= @tournament.modality %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tournament.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@tournament.picture_url, :width => 600) if @tournament.picture.present? %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>